select ut.TYPE_NAME, ut.TYPECODE, nvl(ut.ATTRIBUTES, 0) ATTRIBUTES,  nvl(ut.METHODS, 0) METHODS,
ut.PREDEFINED, ut.INCOMPLETE, ut.FINAL, ut.INSTANTIABLE,
uta.ATTR_NAME, decode(uta.ATTR_TYPE_NAME, 'VARCHAR2', uta.ATTR_TYPE_NAME||'('||uta.LENGTH||')', uta.ATTR_TYPE_NAME) ATTR_TYPE_NAME
from USER_TYPES ut, USER_TYPE_ATTRS uta
where ut.TYPE_NAME = uta.TYPE_NAME (+)
order by ut.TYPE_NAME asc, uta.ATTR_NO asc